name: Beyoojn

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Beyoojn/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: Beyoojn/waka-readme-stats@master
        with:
            WAKATIME_API_KEY: ${{ secrets.WT_TOKEN }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            SHOW_OS: "False"
            SHOW_PROJECTS: "False"
                
