name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap hari
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: beyoojn/waka-readme@v2
        with:
          WAKATIME_API_KEY: ${{ secrets.WT_TOKEN }}
